// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addressbook.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	addressbook.proto
	helloworld.proto

It has these top-level messages:
	Person
	AddressBook
	AddPersonRequest
	AddPersonResponse
	GetAddressBookRequest
	GetAddressBookResponse
	HelloRequest
	HelloReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Person struct {
	Id          int32                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email       string                     `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phones      []*Person_PhoneNumber      `protobuf:"bytes,4,rep,name=phones" json:"phones,omitempty"`
	LastUpdated *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated" json:"last_updated,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

func (m *Person) GetLastUpdated() *google_protobuf.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type Person_PhoneNumber struct {
	Number string           `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	Type   Person_PhoneType `protobuf:"varint,2,opt,name=type,enum=addressbook.Person_PhoneType" json:"type,omitempty"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_MOBILE
}

type AddressBook struct {
	People []*Person `protobuf:"bytes,1,rep,name=people" json:"people,omitempty"`
}

func (m *AddressBook) Reset()                    { *m = AddressBook{} }
func (m *AddressBook) String() string            { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()               {}
func (*AddressBook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

type AddPersonRequest struct {
	Person *Person `protobuf:"bytes,1,opt,name=person" json:"person,omitempty"`
}

func (m *AddPersonRequest) Reset()                    { *m = AddPersonRequest{} }
func (m *AddPersonRequest) String() string            { return proto.CompactTextString(m) }
func (*AddPersonRequest) ProtoMessage()               {}
func (*AddPersonRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddPersonRequest) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

type AddPersonResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *AddPersonResponse) Reset()                    { *m = AddPersonResponse{} }
func (m *AddPersonResponse) String() string            { return proto.CompactTextString(m) }
func (*AddPersonResponse) ProtoMessage()               {}
func (*AddPersonResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddPersonResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AddPersonResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetAddressBookRequest struct {
}

func (m *GetAddressBookRequest) Reset()                    { *m = GetAddressBookRequest{} }
func (m *GetAddressBookRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAddressBookRequest) ProtoMessage()               {}
func (*GetAddressBookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type GetAddressBookResponse struct {
	AddressBook *AddressBook `protobuf:"bytes,1,opt,name=address_book,json=addressBook" json:"address_book,omitempty"`
}

func (m *GetAddressBookResponse) Reset()                    { *m = GetAddressBookResponse{} }
func (m *GetAddressBookResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAddressBookResponse) ProtoMessage()               {}
func (*GetAddressBookResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetAddressBookResponse) GetAddressBook() *AddressBook {
	if m != nil {
		return m.AddressBook
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "addressbook.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "addressbook.Person.PhoneNumber")
	proto.RegisterType((*AddressBook)(nil), "addressbook.AddressBook")
	proto.RegisterType((*AddPersonRequest)(nil), "addressbook.AddPersonRequest")
	proto.RegisterType((*AddPersonResponse)(nil), "addressbook.AddPersonResponse")
	proto.RegisterType((*GetAddressBookRequest)(nil), "addressbook.GetAddressBookRequest")
	proto.RegisterType((*GetAddressBookResponse)(nil), "addressbook.GetAddressBookResponse")
	proto.RegisterEnum("addressbook.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AddressBookService service

type AddressBookServiceClient interface {
	// Add a person to address book
	AddPerson(ctx context.Context, in *AddPersonRequest, opts ...grpc.CallOption) (*AddPersonResponse, error)
	// Get the address book
	GetAddressBook(ctx context.Context, in *GetAddressBookRequest, opts ...grpc.CallOption) (*GetAddressBookResponse, error)
}

type addressBookServiceClient struct {
	cc *grpc.ClientConn
}

func NewAddressBookServiceClient(cc *grpc.ClientConn) AddressBookServiceClient {
	return &addressBookServiceClient{cc}
}

func (c *addressBookServiceClient) AddPerson(ctx context.Context, in *AddPersonRequest, opts ...grpc.CallOption) (*AddPersonResponse, error) {
	out := new(AddPersonResponse)
	err := grpc.Invoke(ctx, "/addressbook.AddressBookService/AddPerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressBookServiceClient) GetAddressBook(ctx context.Context, in *GetAddressBookRequest, opts ...grpc.CallOption) (*GetAddressBookResponse, error) {
	out := new(GetAddressBookResponse)
	err := grpc.Invoke(ctx, "/addressbook.AddressBookService/GetAddressBook", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AddressBookService service

type AddressBookServiceServer interface {
	// Add a person to address book
	AddPerson(context.Context, *AddPersonRequest) (*AddPersonResponse, error)
	// Get the address book
	GetAddressBook(context.Context, *GetAddressBookRequest) (*GetAddressBookResponse, error)
}

func RegisterAddressBookServiceServer(s *grpc.Server, srv AddressBookServiceServer) {
	s.RegisterService(&_AddressBookService_serviceDesc, srv)
}

func _AddressBookService_AddPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServiceServer).AddPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/addressbook.AddressBookService/AddPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServiceServer).AddPerson(ctx, req.(*AddPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressBookService_GetAddressBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServiceServer).GetAddressBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/addressbook.AddressBookService/GetAddressBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServiceServer).GetAddressBook(ctx, req.(*GetAddressBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddressBookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "addressbook.AddressBookService",
	HandlerType: (*AddressBookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPerson",
			Handler:    _AddressBookService_AddPerson_Handler,
		},
		{
			MethodName: "GetAddressBook",
			Handler:    _AddressBookService_GetAddressBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "addressbook.proto",
}

func init() { proto.RegisterFile("addressbook.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xd1, 0x6b, 0xd4, 0x40,
	0x10, 0xc6, 0x9b, 0x34, 0x17, 0x7b, 0x93, 0x72, 0x5c, 0x47, 0xad, 0x21, 0x50, 0x7b, 0xac, 0x2f,
	0x07, 0x85, 0x14, 0xcf, 0x07, 0x41, 0x11, 0xe9, 0x41, 0xa9, 0x62, 0xeb, 0x95, 0xb5, 0x45, 0xd1,
	0x87, 0x92, 0x5c, 0xc6, 0x33, 0xf4, 0x92, 0x5d, 0xb3, 0x89, 0xd0, 0xbf, 0x4e, 0xfc, 0xcf, 0x24,
	0xbb, 0x49, 0xc9, 0x95, 0x5e, 0x9f, 0xb2, 0x33, 0xf3, 0xed, 0xb7, 0xbf, 0x6f, 0xb3, 0xb0, 0x13,
	0x25, 0x49, 0x41, 0x4a, 0xc5, 0x42, 0x5c, 0x87, 0xb2, 0x10, 0xa5, 0x40, 0xaf, 0xd3, 0x0a, 0xf6,
	0x17, 0x42, 0x2c, 0x96, 0x74, 0xa8, 0x47, 0x71, 0xf5, 0xf3, 0xb0, 0x4c, 0x33, 0x52, 0x65, 0x94,
	0x49, 0xa3, 0x66, 0xff, 0x6c, 0x70, 0xcf, 0xa9, 0x50, 0x22, 0xc7, 0x01, 0xd8, 0x69, 0xe2, 0x5b,
	0x23, 0x6b, 0xdc, 0xe3, 0x76, 0x9a, 0x20, 0x82, 0x93, 0x47, 0x19, 0xf9, 0xf6, 0xc8, 0x1a, 0xf7,
	0xb9, 0x5e, 0xe3, 0x13, 0xe8, 0x51, 0x16, 0xa5, 0x4b, 0x7f, 0x53, 0x37, 0x4d, 0x81, 0xaf, 0xc1,
	0x95, 0xbf, 0x44, 0x4e, 0xca, 0x77, 0x46, 0x9b, 0x63, 0x6f, 0xb2, 0x1f, 0x76, 0xb1, 0x8c, 0x7d,
	0x78, 0x5e, 0x2b, 0x3e, 0x57, 0x59, 0x4c, 0x05, 0x6f, 0xe4, 0xf8, 0x0e, 0xb6, 0x97, 0x91, 0x2a,
	0xaf, 0x2a, 0x99, 0x44, 0x25, 0x25, 0x7e, 0x6f, 0x64, 0x8d, 0xbd, 0x49, 0x10, 0x1a, 0xea, 0xb0,
	0xa5, 0x0e, 0x2f, 0x5a, 0x6a, 0xee, 0xd5, 0xfa, 0x4b, 0x23, 0x0f, 0xbe, 0x81, 0xd7, 0x71, 0xc5,
	0x5d, 0x70, 0x73, 0xbd, 0xd2, 0x21, 0xfa, 0xbc, 0xa9, 0xf0, 0x25, 0x38, 0xe5, 0x8d, 0x34, 0x41,
	0x06, 0x93, 0xbd, 0xb5, 0x70, 0x17, 0x37, 0x92, 0xb8, 0x96, 0xb2, 0x03, 0xe8, 0xdf, 0xb6, 0x10,
	0xc0, 0x3d, 0x9b, 0x4d, 0x3f, 0x9e, 0x1e, 0x0f, 0x37, 0x70, 0x0b, 0x9c, 0x0f, 0xb3, 0xb3, 0xe3,
	0xa1, 0x55, 0xaf, 0xbe, 0xce, 0xf8, 0xa7, 0xa1, 0xcd, 0xde, 0x80, 0x77, 0x64, 0x2c, 0xa7, 0x42,
	0x5c, 0xe3, 0x01, 0xb8, 0x92, 0x84, 0x5c, 0x92, 0x6f, 0xe9, 0xdb, 0x78, 0x7c, 0xcf, 0x81, 0xbc,
	0x91, 0xb0, 0xf7, 0x30, 0x3c, 0x4a, 0x92, 0xa6, 0x49, 0xbf, 0x2b, 0x52, 0xa5, 0x31, 0xa8, 0x1b,
	0x3a, 0xc7, 0x7a, 0x83, 0xfa, 0xcb, 0x4e, 0x60, 0xa7, 0x63, 0xa0, 0xa4, 0xc8, 0x15, 0xa1, 0x0f,
	0x8f, 0x54, 0x35, 0x9f, 0x93, 0x52, 0xda, 0x62, 0x8b, 0xb7, 0x65, 0x3d, 0xc9, 0x48, 0xa9, 0x68,
	0xd1, 0xfe, 0xd7, 0xb6, 0x64, 0xcf, 0xe0, 0xe9, 0x09, 0x95, 0x9d, 0x20, 0x0d, 0x0e, 0xbb, 0x84,
	0xdd, 0xbb, 0x83, 0xe6, 0x98, 0xb7, 0xb0, 0xdd, 0x90, 0x5d, 0xd5, 0x68, 0x0d, 0xae, 0xbf, 0x82,
	0xdb, 0xdd, 0xd7, 0x3e, 0xcd, 0xba, 0x98, 0xfc, 0xb5, 0x00, 0x3b, 0xc3, 0x2f, 0x54, 0xfc, 0x49,
	0xe7, 0x84, 0xa7, 0xd0, 0xbf, 0xcd, 0x83, 0x7b, 0x77, 0xad, 0x56, 0x2e, 0x2a, 0x78, 0xbe, 0x6e,
	0x6c, 0xf8, 0xd8, 0x06, 0xfe, 0x80, 0xc1, 0x2a, 0x3b, 0xb2, 0x95, 0x3d, 0xf7, 0x26, 0x0e, 0x5e,
	0x3c, 0xa8, 0x69, 0xcd, 0xa7, 0xce, 0x77, 0x5b, 0xc6, 0xb1, 0xab, 0x5f, 0xe9, 0xab, 0xff, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xc0, 0x98, 0x45, 0x7c, 0x8b, 0x03, 0x00, 0x00,
}
