<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook.proto

namespace Addressbook;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>addressbook.GetAddressBookRequest</code>
 */
class GetAddressBookRequest extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Addressbook::initOnce();
        parent::__construct();
    }

}

