<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook.proto

namespace Addressbook;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>addressbook.Person</code>
 */
class Person extends \Google\Protobuf\Internal\Message
{
    /**
     * Unique ID number for this person.
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string email = 3;</code>
     */
    private $email = '';
    /**
     * Generated from protobuf field <code>repeated .addressbook.Person.PhoneNumber phones = 4;</code>
     */
    private $phones;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_updated = 5;</code>
     */
    private $last_updated = null;

    public function __construct() {
        \GPBMetadata\Addressbook::initOnce();
        parent::__construct();
    }

    /**
     * Unique ID number for this person.
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Unique ID number for this person.
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 3;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .addressbook.Person.PhoneNumber phones = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPhones()
    {
        return $this->phones;
    }

    /**
     * Generated from protobuf field <code>repeated .addressbook.Person.PhoneNumber phones = 4;</code>
     * @param \Addressbook\Person_PhoneNumber[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPhones($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Addressbook\Person_PhoneNumber::class);
        $this->phones = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_updated = 5;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getLastUpdated()
    {
        return $this->last_updated;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_updated = 5;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setLastUpdated($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->last_updated = $var;

        return $this;
    }

}

