<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook.proto

namespace Addressbook;

/**
 * Protobuf enum <code>Addressbook\Person\PhoneType</code>
 */
class Person_PhoneType
{
    /**
     * Generated from protobuf enum <code>MOBILE = 0;</code>
     */
    const MOBILE = 0;
    /**
     * Generated from protobuf enum <code>HOME = 1;</code>
     */
    const HOME = 1;
    /**
     * Generated from protobuf enum <code>WORK = 2;</code>
     */
    const WORK = 2;
}

